#!/bin/bash

#!/bin/bash

script_name=$(basename $0)
descr_str="If a port is being listened, prints the process that is listening to it"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]
    my $script_name <port>

Prints out the pid and the process that is listening to the requested port.
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi

# 

if [ -z "$1" ]; then
    echo "Please provide a port number"
    exit 1
fi

port=$1
if my _isportfree $port; then
    echo "Port $port is free"
    exit 0
fi

lsof -i :$port | grep LISTEN