#!/bin/bash

script_name=$(basename $0)
descr_str="When the command completes will play a sound and show a notification"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	mytils $script_name [--help|--descr]
    mytils lmkwhen [command]

example:
    mytils lmkwhen npm run build

Only works on MacOS, this script will play a sound and show a system
notification when the command completes.
Simply put \`mytils lmkwhen\` before the command you want to run.
"

if mytils isdescr "$1" "$descr_str"; then
	exit 0
fi

if mytils ishelp "$1" "$help_str"; then
	exit 0
fi

# Run the command

"$@"

(mytils notify "$1 Command completed" "Command Completed!") &