#!/bin/bash

script_name=$(basename $0)
descr_str="When the command completes will play a sound and show a notification"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]
    my $script_name [command]

example:
    my lmkwhen npm run build

Only works on MacOS, this script will play a sound and show a system
notification when the command completes.
Simply put \`my lmkwhen\` before the command you want to run.
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi

# Run the command

"$@"

(my notify "$1 Command completed" "Command Completed!") &