#!/bin/bash

show_descr() {
	echo "$1 gamend - git add, and git commit with no changes to the message"
}

if mytils isdescr "$1"; then
	show_descr $2
	exit 0
fi

git add .; git commit --amend --no-edit
