#!/bin/bash

show_descr() {
	echo "gamend - git add, and git commit with no changes to the message"
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-d|--descr)
			show_descr
			exit 0
			;;
		*)
			break
			;;
	esac
done

git add .; git commit --amend --no-edit
