#!/bin/bash

script_name=$(basename $0)
descr_str="git add and ammend last commit with no changes to the message"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]

Shortcut for 'git add .' and 'git commit --amend --no-edit'
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi


# Run the commands

git add .; git commit --amend --no-edit
