#!/bin/bash

script_name=$(basename $0)
descr_str="git commit, add, and push to the remote tracked by the current branch"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	mytils $script_name [--help|--descr]
	mytils $script_name '<commit message>'

This is a shortcut for 
	git add .
	git commit -m '<commit message>'
	git push origin <current branch>
"

if mytils isdescr "$1" "$descr_str"; then
	exit 0
fi

if mytils ishelp "$1" "$help_str"; then
	exit 0
fi
# /////

echo "Starting the process"

if [ -z "$1" ]; then
	echo "Please provide a commit message"
	exit 1
fi

if [ -z "$(git status --porcelain)" ]; then
	echo "No changes to commit"
	exit 1
fi

master_or_main=$(git branch --show-current | grep -E 'main|master')

if [ -z "$master_or_main" ]; then
	echo "Not on main or master branch"
	exit 1
fi

echo "Adding changes"
git add .

echo "Creating the commit"
git commit -m "$1"

echo "Pushing to master"
git push origin "$master_or_main"
