#!/bin/bash

show_descr() {
	echo "gru - Git review upload change to gerrit"
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-d|--descr)
			show_descr
			exit 0
			;;
		*)
			break
			;;
	esac
done

git review -R
