#!/usr/bin/env bash

script_name=$(basename $0)
descr_str="Base script for all other utility scripts"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]

This script does nothing. Its purpose is to be copied and pasted
into a new utility as a guide of how to structure and integrate it
with the my infrastructure.
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi

if my iscat "$1" "$0"; then
	exit 0
fi

echo "This script does nothing, it should be used as an example for other scripts"