#!/bin/bash

show_descr() {
	echo "rmreview - Remove all Git Review (gerrit) branches from local repository"
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-d|--descr)
			show_descr
			exit 0
			;;
	esac
done

git branch --list 'review*' | xargs -r git branch -D
