#!/bin/bash

show_descr() {
	echo "$1 rmreview - Remove all Git Review (gerrit) branches from local repository"
}

is_descr=$(mytils isdescr "is$1")

if mytils isdescr "$1"; then
	show_descr $2
	exit 0
fi

git branch --list 'review*' | xargs -r git branch -D
