#!/bin/bash

show_descr() {
	echo "$1 seescripts - Prints the 'scripts' object from package.json"
}

if mytils isdescr "$1"; then
	show_descr $2
	exit 0
fi

if [ ! -f package.json ]; then
	echo "package.json not found"
	exit 1
fi

cat package.json | jq "{scripts}"
