#!/bin/bash

show_descr() {
	echo "seescripts - Prints the 'scripts' object from package.json"
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-d|--descr)
			show_descr
			exit 0
			;;
	esac
done


cat package.json | jq "{scripts}"
