#!/bin/bash

show_descr() {
	echo "serve - Start up a local web server and serve the current directory"
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-d|--descr)
			show_descr
			exit 0
			;;
	esac
done


python -m http.server
