#!/bin/bash

show_descr() {
	echo "$1 serve - Start up a local web server and serve the current directory"
	echo "$1  | Usage: serve [port]"
}

if mytils isdescr "$1"; then
	show_descr $2
	exit 0
fi

port=8000
if [[ -n "$1" ]]; then
	port=$1
fi

python -m http.server "$port"
