#!/bin/bash

script_name=$(basename $0)
descr_str="Download changes from gerrit for review"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]
	my $script_name 

Shortcut for 'git review -d'
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi


# ////

git review -d
