#!/bin/bash

script_name=$(basename $0)
descr_str="Git review upload change to gerrit"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]

Shortcut for 'git review -R'
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi

# Process

git review -R
