#!/bin/bash

script_name=$(basename $0)
descr_str="Starts a cached proxy configured to cache dev IVAAP"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	my $script_name [--help|--descr]

Starts a cached proxy configured to cache all requests from 
https://dev.ivaap.int.com. 
The proxy will run on port 9912. You will need to configure your
browser to use SOCKS5 proxy on 127.0.0.1:9912
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi

if my iscat "$1" "$0"; then
	exit 0
fi

_run_proxy() {
    my cachedproxy --port 9912 --patterns "https://dev\.ivaap\.int\.com.*"
}

_run_proxy
