#!/bin/bash

mytils_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
scripts_path="$mytils_path/scripts"
bold=$(tput bold)
normal=$(tput sgr0)

printdir() {
	echo "$2:"
	# echo "printing contents of $1"
	for f in "$1"/*; do 
		# echo "  $f"
		f_name=$(basename $f)
		if [[ -f "$f" && -x "$f" ]]; then 
			echo "- ${bold}$f_name${normal} - $($f --descr)"
		fi
	done
}

if [[ -z "$1" || "$1" == "list" ]]; then
	echo
	echo "Available Utilities:"
	echo "--------------------"
	printdir "$scripts_path" "Base"

	for f in "$scripts_path"/*; do
		if [ -d "$f" ]; then
			f_name=$(basename $f)
			if [[ "$f_name" == "internal" ]]; then
				continue
			fi
			printdir $f "$(basename $f)"
		fi
	done
	echo
else
	# echo "Searching for script $1 in $scripts_path"
    # for file in "$scripts_path"/**/*; do
	# 	# echo "checking $file"
	# 	filename=$(basename $file)
	# 	echo "filename: $filename == $1"
	# 	if [[ -f "$file" && -x "$file" && "$filename" == "$1" ]]; then
	# 		# echo "running command: $file ${@:2}"
	# 		"$file" "${@:2}"
	# 		exit 0
	# 	fi
	# done
	# echo "Script $1 not found"

    # echo "Searching for script $1 in $scripts_path"
	for file in $(find "$scripts_path" -type f -perm -u=x); do
		filename=$(basename "$file")
		if [[ "$filename" == "$1" ]]; then
			"$file" "${@:2}"
			exit $?
		fi
	done
	echo "Script $1 not found"
fi

