#!/bin/bash

mytils_script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ $1 == "list" ]; then
	echo
	echo "Available utilities:"
	echo "--------------------"
	for f in $mytils_script_path/scripts/*; do 
		if [ -x $f ]; then 
			$f --descr
		fi
	done
	echo
else
	~/src/Utils/bash/scripts/"$1" "${@:2}"
fi
