#!/bin/bash

script_name=$(basename $0)
descr_str="Checks if the requested port is free or being listened to"
help_str="
$descr_str
------------------------------------------------------------------
usage: 
	mytils $script_name [--help|--descr]
    mytils $script_name <port>

Prints out the status of the requested port.
"

if mytils isdescr "$1" "$descr_str"; then
	exit 0
fi

if mytils ishelp "$1" "$help_str"; then
	exit 0
fi

if [ -z "$1" ]; then
    echo "Please provide a port number"
    exit 1
fi

port=$1

if mytils _isportfree $port; then
    echo "Port $port is free"
else
    echo "Port $port is being listened to"
fi