#!/bin/bash

script_name=$(basename $0)
descr_str="Start up a local web server and serve the current directory"
help_str="
$descr_str
------------------------------------------------------------------
usage:	
	my $script_name [--help|--descr]
	my serve [port=8000]

Uses Python http module to start a web server and serve the current 
directory. The default port is 8000, but can be changed by passing
a port number as an argument.
"

if my isdescr "$1" "$descr_str"; then
	exit 0
fi

if my ishelp "$1" "$help_str"; then
	exit 0
fi

#/////
show_descr() {
	echo "$1 serve - Start up a local web server and serve the current directory"
	echo "$1  | Usage: serve [port]"
}

if my isdescr "$1"; then
	show_descr $2
	exit 0
fi

port=8000
if [[ -n "$1" ]]; then
	port=$1
fi

python -m http.server "$port"
